name: PHP 8.1 Compliant

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  php81-compatibility:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up PHP 8.1
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install dependencies
        run: composer install --ignore-platform-reqs
      - name: Run PHP 8.1 Compliant
        run: php -l .
